package fr.aelysya.pokinator.utility;

public enum Attribute {
    NUMBER, NAME, GENERATION, FIRST_TYPE, TEST, WEAKNESSES, STATS, SIZE, WEIGHT, LEGENDARY_STATUS, EGG_STEPS, CAPTURE_RATE, MAX_EXPERIENCE;
}
